version: 2.0
jobs:
  build:
    docker:
      - image: clojure:lein-2.8.1
    working_directory: ~/circleci.test
    steps:
      - checkout

      - cache-restore:
          # always restore the latest cache
          key: v1-jars-

      - run: lein test

      - cache-save:
          key: v1-jars-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
